image: docker:latest

services:
  - docker:dind

before_script:
   - apt-get update; apt-get --no-install-recommends install make

build:
  stage: build
  script:
    - make map-clean
    - make map-build
