image: docker:latest

services:
  - docker:dind

cache:
  paths:
  - data/

before_script:
   - apk add --no-cache make coreutils wget

build:
  stage: build
  tags:
  - dind
  script:
#    - ln -s /cache $(pwd)/data
    - make map-clean
#    - make map-build
    - make map-fetch
#    - ls -lad $(pwd)/data
#    - pwd; ls -la $(pwd)/data/
#    - ls -la /builds/docker-container/docker-osrm-backend-volume/
#    - ls -la /builds/docker-container/docker-osrm-backend-volume/data/
#    - docker run -t -v $(pwd)/data:/data osrm/osrm-backend ls -la /data/
    - make map-extract
    - make map-contract
