image: docker:latest

services:
  - docker:dind

before_script:
   - apk add --no-cache make coreutils wget

build:
  stage: build
  script:
    - make map-clean
#    - make map-build
    - make map-fetch
    - pwd; ls -la $(pwd)/data/
    - docker run -t -v $(pwd)/data:/data osrm/osrm-backend ls -la /data/
    - make map-extract
    - make map-contract
