sudo: required
dist: trusty
language: c

services:
  - docker

install:
  - make build

script:
  - test "$(docker run --rm -it tmtde/osrm-backend-volume osrm-routed -h | head -1 | tail -1 | cut -d' ' -f1)" = "osrm-routed"
